# -*- coding: utf-8 -*-
"""Data_Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T4AWusn-QRoU3NY5J-5k7iWt6QXZx_qE

##Data Cleaning
Exploring the data that was fetched and after per
"""

import pandas as pd
import numpy as np
import pandas_datareader as web
import matplotlib.pylab as plt
import seaborn as sns
from scipy import stats

plt.style.use('ggplot')
pd.set_option('display.max_columns',100)

df = pd.read_csv('/content/Stock.csv')
df.index = pd.to_datetime(df['Unnamed: 0'])
df.columns

df = df[['open', 'high', 'low', 'close', 'adjusted close',
       'volume']]
df = df.rename_axis('Index')
df

"""No missing values to find

"""

df.isna().sum()

"""Visually no outliers can be seen
Mathmetical calculation will be used for further analysis

"""

plt.scatter(df['close'],df['open'])
plt.xlabel('Close')
plt.ylabel('Open')
plt.title('Outliers Detection')
plt.show()

z_scores = np.abs(stats.zscore(df['close']))

# Set threshold
threshold = 3

# Identify outliers
outliers = np.where(z_scores > threshold)[0]

outliers